<?php

/**
 * @file
 * Hooks for wuzi_blocks module.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function wuzi_blocks_theme($existing, $type, $theme, $path) {
  return [
    'wuzi_blocks_catalog_tree' => [
      'variables' => ['tree' => []],
      'template' => 'catalog-tree',
    ],
    'universal_term_products' => [
      'variables' => ['rendered_products' => [], 'term' => NULL],
    ],
  ];
}
