_core:
  default_config_hash: 4bQlG9nX40H6RYr1oMGvC0OQ_EGyNS_075_dl8JcrmE
favicon:
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  use_default: true
container_width: '1260'
header_width: header_width_contained
main_width: main_width_contained
footer_width: footer_width_contained
all_icons_show: 1
facebook_url: ''
twitter_url: ''
instagram_url: ''
linkedin_url: ''
youtube_url: ''
whatsapp_url: empty
github_url: ''
telegram_url: empty
vimeo_url: ''
highlight_author_comment: 0
node_author_pic: 0
node_tags: 0
copyright_text: 1
scrolltotop_on: 1
css_extra: 0
css_code: ''
vk_url: empty
slider_style_options: slider_three
