features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: 'public://logo2.svg'
favicon:
  use_default: 1
container_width: '1260'
header_width: header_width_contained
main_width: main_width_contained
footer_width: footer_width_contained
all_icons_show: 1
facebook_url: ''
twitter_url: ''
instagram_url: ''
linkedin_url: ''
youtube_url: ''
vimeo_url: ''
vk_url: empty
whatsapp_url: empty
github_url: ''
telegram_url: empty
slider_style_options: slider_three
scrolltotop_on: 1
copyright_text: 1
css_extra: 0
css_code: ''
highlight_author_comment: 0
